[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmds = [". .venv/bin/activate && python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"]
